[project]
authors = ["Kaid <kaid@kaid.me>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "indie_musicians"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.6,<4"
polars = ">=1.7.1,<2"
jupyter = ">=1.1.1,<2"
aiohttp = ">=3.10.5,<4"
uvloop = ">=0.20.0,<0.21"
pycryptodome = ">=3.20.0,<4"
gradio = ">=4.44.0,<5"
xlsxwriter = ">=3.2.0,<4"
openpyxl = ">=3.1.5,<4"
pyarrow = ">=17.0.0,<18"
